### PR TITLE
feat(exercises): add hello-world

### PR DESCRIPTION
**Pull request by 0xE282B0**

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
Thanks for the PR! One small nit: the `.docs/instructions.md` document is empty. As this is a practice exercise, it is easy enough to populate it. First, fetch configlet via `bin/fetch-configlet`. Then run `./bin/configlet sync --update --exercise hello-world --yes`

**Comment by ErikSchierboom** [comment]
@0xE282B0 There is an error in the JSON config file: https://github.com/exercism/gnucobol/runs/7113861945?check_suite_focus=true

**Comment by 0xE282B0** [comment]
Sorry for that, I fixed the JSON file.

**Comment by ErikSchierboom** [comment]
@0xE282B0 It looks like something went wrong and this PR was closed. Maybe you deleted the branch on the remote? Could you re-create the PR?

**Comment by 0xE282B0** [comment]
Sure, see: https://github.com/exercism/gnucobol/pull/8 😊

**Pull request closed without merging**
